// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'extra-columns-menu-clean'
  | 'extra-columns-menu-clean-item'
  | 'extra-columns-menu-no-fields'
  | 'extra-columns-menu-root'
  | 'extra-columns-section-head'
  | 'extra-columns-section-sidenav';
